services:
  - type: web
    name: dronox-core-network
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn drono_guard_bot:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
